### ISSUE TITLE
org.apache.spark.sql.AnalysisException: undefined function mcount

### ISSUE THREAD

**Issue by amaia00** [ashkapsky/BigDatalog#10]
Hi,

I was trying to execute un script using PageRank algorithm, so, I defined a schema like this:

```
database({ node(N:double), edge(S:double, Sink:double), edgeCount(S:double, Cnt:double) }).
rank(Inc, N, msum<R>) <- node(N), Inc = 1, R = 0.15 / N.
rank(Incp, N, msum<R>) <- rank(Inc, P, RP), edge(P,N), edgeCount(P, Cnt), Cnt > 0, R = 0.85 * RP / Cnt, Incp = Inc + 1.
```

However, when I try to execute I got this error:

```
Exception in thread "main" org.apache.spark.sql.AnalysisException: undefined function mcount;
	at org.apache.spark.sql.catalyst.analysis.SimpleFunctionRegistry$$anonfun$2.apply(FunctionRegistry.scala:65)
	at org.apache.spark.sql.catalyst.analysis.SimpleFunctionRegistry$$anonfun$2.apply(FunctionRegistry.scala:65)
	at scala.Option.getOrElse(Option.scala:120)
	at org.apache.spark.sql.catalyst.analysis.SimpleFunctionRegistry.lookupFunction(FunctionRegistry.scala:64)
	at org.apache.spark.sql.catalyst.analysis.Analyzer$ResolveFunctions$$anonfun$apply$12$$anonfun$applyOrElse$5$$anonfun$applyOrElse$24.apply(Analyzer.scala:574)
	at org.apache.spark.sql.catalyst.analysis.Analyzer$ResolveFunctions$$anonfun$apply$12$$anonfun$applyOrElse$5$$anonfun$applyOrElse$24.apply(Analyzer.scala:574)
	at org.apache.spark.sql.catalyst.analysis.package$.withPosition(package.scala:48)
	at org.apache.spark.sql.catalyst.analysis.Analyzer$ResolveFunctions$$anonfun$apply$12$$anonfun$applyOrElse$5.applyOrElse(Analyzer.scala:573)
	at org.apache.spark.sql.catalyst.analysis.Analyzer$ResolveFunctions$$anonfun$apply$12$$anonfun$applyOrElse$5.applyOrElse(Analyzer.scala:570)
	at org.apache.spark.sql.catalyst.trees.TreeNode$$anonfun$3.apply(TreeNode.scala:259)
	at org.apache.spark.sql.catalyst.trees.TreeNode$$anonfun$3.apply(TreeNode.scala:259)
	at org.apache.spark.sql.catalyst.trees.CurrentOrigin$.withOrigin(TreeNode.scala:69)
	at org.apache.spark.sql.catalyst.trees.TreeNode.transformDown(TreeNode.scala:258)
	at org.apache.spark.sql.catalyst.trees.TreeNode$$anonfun$transformDown$1.apply(TreeNode.scala:264)
	at org.apache.spark.sql.catalyst.trees.TreeNode$$anonfun$transformDown$1.apply(TreeNode.scala:264)
	at org.apache.spark.sql.catalyst.trees.TreeNode$$anonfun$4.apply(TreeNode.scala:281)
	at scala.collection.Iterator$$anon$11.next(Iterator.scala:328)
	at scala.collection.Iterator$class.foreach(Iterator.scala:727)
	at scala.collection.AbstractIterator.foreach(Iterator.scala:1157)
...
```
I'm not trying to use the `mcount` function, but apparently the program is trying to call it.
Thanks!

**Comment by amaia00** [comment]
Apparently `mcount` and `msum` operation aren't implemented yet.  :(

https://github.com/ashkapsky/BigDatalog/blob/0070c65bb8b32fbf0b0e3a284c5a51519f48c6c9/datalog/src/main/scala/edu/ucla/cs/wis/bigdatalog/spark/execution/setrdd/AggregateSetRDD.scala#L147
